"""created education experience user blog for portfolio

Revision ID: ddd5c00b4aec
Revises: 3eda89cbbab0
Create Date: 2024-01-02 20:23:52.657767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd5c00b4aec'
down_revision: Union[str, None] = '3eda89cbbab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
